// Module included in the following assemblies:
//
// * machine_management/creating_machinesets/creating-machineset-aws.adoc
// * machine_management/creating_machinesets/creating-machineset-gcp.adoc
// * machine_management/creating_machinesets/creating-machineset-azure.adoc

ifeval::["{context}" == "creating-machineset-aws"]
:aws:
endif::[]
ifeval::["{context}" == "creating-machineset-azure"]
:azure:
endif::[]
ifeval::["{context}" == "creating-machineset-gcp"]
:gcp:
endif::[]

[id="machineset-creating-non-guaranteed-instance_{context}"]
ifdef::aws[= Creating Spot Instances]
ifdef::azure[= Creating Spot VMs]
ifdef::gcp[= Creating preemptible VM instances]

ifdef::aws[You can launch a Spot Instance on AWS by adding SpotMarketOptions to your MachineSet YAML file.]
ifdef::azure[You can launch a Spot VM on Azure by adding SpotVMOptions to your MachineSet YAML file.]
ifdef::gcp[You can launch a preemptible VM instance on GCP by adding the `Preemptible` field to your MachineSet YAML file.]

.Procedure
* Add the following line under the `providerSpec` field:
+
ifdef::aws[]
[source,yaml]
----
providerSpec:
  value:
    spotMarketOptions: {} <1>
----
<1> You can optionally set the `maxPrice` for the `spotMarketOptions` field to limit the cost of the Spot Instance, for example `maxPrice: '2.50'`.
If the `maxPrice` is set, this value is used as the hourly maximum spot price. If not set, the maximum price defaults to charge up to the On-Demand Instance price.

[NOTE]
====
It is strongly recommended to use the default On-Demand price as the `maxPrice` value and to not set the maximum price for Spot Instances.
====
endif::aws[]
ifdef::azure[]
[source,yaml]
----
providerSpec:
  value:
    spotVMOptions: {} <1>
----
<1> You can optionally set the `maxPrice` for the `spotVMOptions` field to limit the cost of the Spot VM, for example `maxPrice: '0.98765'`.
If the `maxPrice` is set, this value is used as the hourly maximum spot price. If not set, the maximum price defaults to `-1` and charges the current price, up to the standard VM price.
Azure caps Spot VM prices at the standard price and will not evict an instance due to pricing if the instance is set with the default `maxPrice`.
However, an instance can still be evicted due to capacity restrictions.

[NOTE]
====
It is strongly recommended to use the default standard VM price as the `maxPrice` value and to not set the maximum price for Spot VMs.
====
endif::azure[]
ifdef::gcp[]
[source,yaml]
----
providerSpec:
  value:
    preemptible: true <1>
----
<1> After the instance is launched, the Machine is labelled as an `interruptable-instance` if this field is set to `true`.
endif::gcp[]
